### ISSUE TITLE
xcscope.el and user-reserved keybindings collision

### ISSUE THREAD

**Issue by domo141** [dkogan/xcscope.el#10]
According to http://www.gnu.org/software/emacs/manual/html_node/elisp/Key-Binding-Conventions.html
C-c <letter>, letter being [A-Za-z] are reserved for users.

The keybinding prefix C-c s collides with this convention.

I suggest that this prefix is changed to something else (and perhaps the C-c s binding is kept
as deprecated alternative in case user has not defined C-c s herself), and information is added
how user can re-map C-c s to this keymap if she so chooses (it is reserved for her, anyway).

**Comment by dkogan** [comment]
Hmm. These key bindings were set this way for a LONG time. But yes, complying with the standard is important. I'll do something...

**Comment by dkogan** [comment]
Hi. This is now made customizable by the merged pull request in #12.

**Comment by domo141** [comment]
Good. Tnx. Now I just have to figure out good prefix for me.
