### ISSUE TITLE
"display-buffer" fallbacks to "display-buffer-fallback-action"

### ISSUE THREAD

**Issue by litvindev** [dkogan/xcscope.el#13]
Parentheses are missed here:
`(defvar cscope-display-buffer-args
  (and (not cscope-running-in-xemacs)
       (>= emacs-major-version 24)
       '(display-buffer-use-some-window (inhibit-same-window . t)))
`

Should be:
`(defvar cscope-display-buffer-args
  (and (not cscope-running-in-xemacs)
       (>= emacs-major-version 24)
       '((display-buffer-use-some-window (inhibit-same-window . t))))
`

**Comment by dkogan** [comment]
Hi. Thank you very much for the report. I just released version 1.2 that includes this fix.
