### ISSUE TITLE
MacOS: xcscope.el can't be run within emacs 

### ISSUE THREAD

**Issue by andrewhit** [dkogan/xcscope.el#16]
I just downloaded xcscope.el and add the below 2 lines to my .emacs on my own MacOS.

> (load-file "~/xcscope/xcscope.el")
> (require 'xcscope)

My emacs version is 22.1.1.

However when I run # emacs --debug-init, I met the below error. 

> Debugger entered--Lisp error: (error "Unknown keyword :risky")
>   signal(error ("Unknown keyword :risky"))
>   error("Unknown keyword %s" :risky)
>   custom-handle-keyword(cscope-keymap-prefix :risky t custom-variable)
>   custom-declare-variable(cscope-keymap-prefix "^Cs" "Prefix for key bindings of `cscope-minor-mode'.\n\nChanging this variable outside Customize does not have any\neffect.  To change the keymap prefix from Lisp, you need to\nexplicitly re-define the prefix key:\n\n    (define-key cscope-minor-mode-keymap cscope-keymap-prefix nil)\n    (setq cscope-keymap-prefix (kbd \"C-c ,\"))\n    (define-key cscope-minor-mode-keymap cscope-keymap-prefix\n                cscope-command-map)" :group cscope :type string :risky t :set (lambda (variable key) (when (and ... ...) (define-key cscope-minor-mode-keymap ... nil) (define-key cscope-minor-mode-keymap key cscope-command-map)) (set-default variable key)))
>   (defcustom cscope-keymap-prefix "^Cs" "Prefix for key bindings of `cscope-minor-mode'.\n\nChanging this variable outside Customize does not have any\neffect.  To change the keymap prefix from Lisp, you need to\nexplicitly re-define the prefix key:\n\n    (define-key cscope-minor-mode-keymap cscope-keymap-prefix nil)\n    (setq cscope-keymap-prefix (kbd \"C-c ,\"))\n    (define-key cscope-minor-mode-keymap cscope-keymap-prefix\n                cscope-command-map)" :group (quote cscope) :type (quote string) :risky t :set (lambda (variable key) (when ... ... ...) (set-default variable key)))
>   eval-buffer(#<buffer  *load*<2>> nil "/Users/zhuangyan/xcscope/xcscope.el" nil t)  ; Reading at buffer position 50383
>   load-with-code-conversion("/Users/zhuangyan/xcscope/xcscope.el" "/Users/zhuangyan/xcscope/xcscope.el" nil nil)
>   load("/Users/zhuangyan/xcscope/xcscope.el" nil nil t)
>   load-file("~/xcscope/xcscope.el")
>   eval-buffer(#<buffer  *load*> nil "/Users/zhuangyan/.emacs" nil t)  ; Reading at buffer position 8630
>   load-with-code-conversion("/Users/zhuangyan/.emacs" "/Users/zhuangyan/.emacs" t t)
>   load("~/.emacs" t t)
>   #[nil "^H<85>¾^@      Æ=<83>^Q^@Ç^HÈQ<82>A^@  É=<83>3^@ÊÇËÌ#<83>#^@Í<82>A^@ÊÇËÎ#<83>/^@Ï<82>A^@Í<82>A^@       Ð=<83>=^@Ñ<82>A^@Ç^HÒQ^ZÓ^SÔ\nÓ<89>#<88>^KÓ=<83>i^@ÕÖ×Ç^HØQ!\"^\Ô\fÓ<89>#<88>^KÓ=<83>h^@\n^S)^K<83>®^@Ù^K!Ú<9a><83>®^@Û^K!<89>^]ÜP^^$Ý^N$!<83><8a>^@^N$<82><95>^@Ý^M!<83><94>^@^M<82><95>^@Ë<89>^U<83>­^@Þ^M^K\"<83>«^@ßà^M^K#<88>áâ!<88>^M^S*^N%?<85>½^@Ë^^&ÔãÓ<89>#))<87>" [init-file-user system-type user-init-file-1 user-init-file otherfile source ms-dos "~" "/_emacs" windows-nt directory-files nil "^\\.emacs\\(\\.elc?\\)?$" "~/.emacs" "^_emacs\\(\\.elc?\\)?$" "~/_emacs" vax-vms "sys$login:.emacs" "/.emacs" t load expand-file-name "init" file-name-as-directory "/.emacs.d" file-name-extension "elc" file-name-sans-extension ".el" file-exists-p file-newer-than-file-p message "Warning: %s is newer than %s" sit-for 1 "default" alt inhibit-default-init inhibit-startup-message] 7]()
>   command-line()
>   normal-top-level()
>

**Comment by andrewhit** [comment]
Then I downloaded cscope-15.8b from the below link. And it includes two files, cscope-indexer and xcscope.el under contrib/xcscope.

https://sourceforge.net/projects/cscope/files/latest/download?source=files

The I changed the above lines as below within my .emacs files.

> (load-file "~/bin/cscope-15.8b/xcscope.el")
> (require 'xcscope)

Then I ran emacs and "Cscope" occurs in the menu bar and everything is fine.

For example, I can use "Control c s s" to find the references to the symbol.

**Comment by dkogan** [comment]
Hi. Thanks for the report. You're using emacs 22, which was released in 2007. It is too old. I guess I'm using something not available in such an old release. If you want to send me patches that would make it compatible, I'll look at them. Otherwise, you should upgrade to a more recent emacs release.

Thanks
