### ISSUE TITLE
"Cscope" does not show in the menu bar of Emacs 26.1 or Emacs 25.3.1

### ISSUE THREAD

**Issue by andrewhit** [dkogan/xcscope.el#17]
Hi Dima,

I did the two test cases on my own iMac.

Case A
1) I downloaded Emacs Mac Port which uses Gnu Emacs 26.1
https://github.com/railwaycat/homebrew-emacsmacport

- Use xcscope.el provided here
> (load-file "~/bin/xcscope.el")
> (require 'xcscope)

2) Then I ran emacs and "Cscope" is not shown in the menu bar.
<img width="543" alt="screen shot 2018-04-19 at 9 51 26 am" src="https://user-images.githubusercontent.com/6918414/38966929-3fa8455c-43b7-11e8-89c3-a25b74d3b3c0.png">

So when I click "Control C S S", "s" character is input.

Case B:
1) Install emacs via brew
brew install emacs // to get Emacs 25.3.1

- Use xcscope.el provided here
> (load-file "~/bin/xcscope.el")
> (require 'xcscope)

2) Then I ran emacs and I met the same issue as case A, "Cscope" does not show in the menu bar.

Regards,
Andrew

**Comment by andrewhit** [comment]
After adding the below line into my .emacs, Cscope can be run in emacs.

> (cscope-setup)

Closing this issue.

**Comment by sonnycloudtp** [comment]
The solutions presented above didn't work in emacs 26.1

**Comment by dkogan** [comment]
In its most basic form, open emacs without any of your own configuration, load xcscope-el, and see if you get a menu. Do this from the xcscope-el directory:

```emacs -Q xcscope.el --eval '(progn (eval-buffer (current-buffer)) (cscope-minor-mode))'
```

If you get a menu, your local config is breaking stuff. If you don't get a menu, I guess tell me your emacs version, and I can take a look when I get time.
