### ISSUE TITLE
Tramp support

### ISSUE THREAD

**Issue by dlandro** [dkogan/xcscope.el#24]
Hi,

I've been using xcscope for awhile locally.  I recently started to use Tramp and was interested in using xcscope over Tramp, but don't really know how to set it up.  Wondering if you can point me to some instructions on how to get it working.

Thanks!

**Comment by dlandro** [comment]
Figured out my problem.  Needed to create a cscope file with relative paths in my remote directory.  My original file had absolute paths and it wasn't working.

**Comment by dkogan** [comment]
You shouldn't have to do anything special:

1. Open any remote file in your project over TRAMP
2. Make an index (C-c s I)
3. Search.
