### ISSUE TITLE
Support for inline functions

### ISSUE THREAD

**Issue by chhajedji** [dkogan/xcscope.el#25]
Hello there,

I found cscope is a great tool to navigate in a large project. Using it since a long time.1 issue I am facing is if a function is defined as `inline`, then `cscope-find-global-definition` doesn't show that function. Please add this functionality. Thanks.

**Comment by dkogan** [comment]
Hi. xcscope-el is just an interface to the cscope tool. THAT tool does all the work, and you should file a bug report there: https://sourceforge.net/p/cscope/bugs/
