### ISSUE TITLE
How to change the behavior of quitting cscope display buffer

### ISSUE THREAD

**Issue by wanghaiqiangk** [dkogan/xcscope.el#26]
When press `q`, the cscope display buffer is closed and replaced with a second source code buffer. Therefore, there are two buffers for the source code and I have to manually kill one of them.

I hope, when press `q`, the cscope display buffer can be completely closed and return the focus to source code buffer. I think this can be customized by modifying `cscope-display-buffer-args`, do you have any idea about how to change and achieve this feature?

**Comment by dkogan** [comment]
Hi. First of all, `cscope-display-buffer-args` controls how the *cscope*
buffer pops up, not how it disappears. So this variable doesn't do
anything here.

Currently 'q' effectively calls (bury-buffer), which produces the
behavior you describe. I just ran a few quick experiments, and in all
cases, you end up with two identical source windows visible. I tried
(quit-window) and I tried to just kill the *cscope* buffer. What EXACTLY
do you think 'q' should do? And better yet, can you point to a built-in
emacs function that has that behavior?

**Comment by wanghaiqiangk** [comment]
I managed to figure out how and that's what you said.

I changed `(bury-buffer)` to `(quit-window)` in `cscope-bury-buffer`. Since `quit-window` also evokes `bury-buffer`, the `*cscope*` is the least candidate for switching buffer. To bring `*cscope*` to the first one, maybe a simple `(delete-window)` can work.

I prefer the behaviour of killing the window. Because I want to focus on the source code window. After finishing the use of cscope, I don't want to invoke extra typing to just close its buffer/window. But maybe some people prefer the original one. Thereby, an option to control such behaviour can be a choice.

I created a PR and please check it.

**Comment by dkogan** [comment]
So to be clear: (quit-window) does what you want and (bury-window)
doesn't?

**Comment by wanghaiqiangk** [comment]
That's it.

**Comment by dkogan** [comment]
Fixed in https://github.com/dkogan/xcscope.el/commit/8e441efab0757778fe3594ff68c378bf90f539f9
