### ISSUE TITLE
does xcscope support symbolic link file ?

### ISSUE THREAD

**Issue by ChinaXing** [dkogan/xcscope.el#8]
I use scope-index to generate the TAGS file  cscope configure file.

but it will produce following errors : 

```
cscope: cannot find file lib/inets/test/httpc_SUITE_data/cgi_echo.c
```

which is a symbolic link to other file : 
```
gi_echo.c -> ../httpd_SUITE_data/cgi_echo.c
```

the file is exist.

so I am not sure does this error cause by symbolic link file not supported by xcscope ?

**Comment by dkogan** [comment]
This is a cscope (not xcscope) issue: https://sourceforge.net/p/cscope/bugs/214/
